[package]
name = "guestjs-llrt"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
guestjs-macros = { path = "../guestjs-macros", version = "0.1.7" }
guestjs-core = { path = "../guestjs-core", version = "0.1.7" }

bytes = { workspace = true, optional = true }
futures = { workspace = true, optional = true }

llrt_modules = { git = "https://github.com/awslabs/llrt", rev = "101ae49", default-features = false, features = ["path", "timers"] }
rquickjs = { workspace = true, optional = true }

[dev-dependencies]
tempfile = "3"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[features]
default = []
buffer = ["llrt_modules/buffer"]
console = ["llrt_modules/console"]
fetch = [
    "llrt_modules/abort",
    "llrt_modules/buffer",
    "llrt_modules/fetch",
    "llrt_modules/stream-web",
    "llrt_modules/tls-ring",
    "llrt_modules/url",
    "streams",
]
fs = ["llrt_modules/buffer", "llrt_modules/fs"]
os = ["llrt_modules/os"]
process-env = ["dep:rquickjs"]
streams = [
    "dep:rquickjs",
    "dep:bytes",
    "dep:futures",
    "guestjs-core/bytes",
    "llrt_modules/stream-web",
]
timers = ["llrt_modules/timers"]
url = ["llrt_modules/url"]
